### ISSUE TITLE
Could you make a tutorial please? Thanks

### ISSUE THREAD

**Issue by persanoadorno** [fatih-yavuz/links.dev#104]

**Comment by fatih-yavuz** [comment]
I know that @codingwithdidem has a plan on recording a tutorial but I don't know if it is going to be in English. If not, any volunteering is welcome and we can place the video URL in the README.md

**Comment by codingwithdidem** [comment]
Ingilizce cekebilirim aksama cekmek var aklimda uygunsa senin icinde

27 Ara 2022 Sal 13:47 tarihinde Fatih Yavuz ***@***.***> şunu
yazdı:

**Comment by fatih-yavuz** [comment]
She's done it @persanoadorno you can find it here: https://www.youtube.com/watch?v=50oHDXGuqNQ
