### ISSUE TITLE
i am not able to add my username

### ISSUE THREAD

**Issue by mohanshetty** [fatih-yavuz/links.dev#110]
not able to create my username here

**Comment by fatih-yavuz** [comment]
Your PR checks were failing for different reasons. Your latest PR #109 passed the pipeline and it's been merged

**Comment by mohanshetty** [comment]
[links.dev](https://github.com/fatih-yavuz/links.dev)/registry.yaml

my name registered on this file but https://links.dev/mohanshetty this showing page not found

**Comment by fatih-yavuz** [comment]
You can look at the FAQ section for the reason. In the meantime, I
invalidated the cache for you.

**Comment by mohanshetty** [comment]
now working thank you

**Comment by mohanshetty** [comment]
How to add custom js like adding custom css
