### ISSUE TITLE
Suggestion: Make URL not case sensitive

### ISSUE THREAD

**Issue by xYundy** [fatih-yavuz/links.dev#114]
For now when we publish a site for ex. `https://links.dev/xYundy/` it will be shown, but if I try to access `https://links.dev/xyundy/` I'll get 404. 

I think URL's should be not case sensitive. If this is requested behaviour - maybe an aliases will be a good thing?

**Comment by fatih-yavuz** [comment]
This is not intended. Thanks for letting me know that. I will fix it

**Comment by fatih-yavuz** [comment]
This should be fixed now @xYundy
