### ISSUE TITLE
Suggestion: CI only work for newly added username/domain

### ISSUE THREAD

**Issue by haliliceylan** [fatih-yavuz/links.dev#125]
Hi,

Now CI checks the previous usernames every time it runs. A previously added user's problematic web page can explode CI.

To fix this, only the newly added username/domain should be checked under PR.

**Comment by bsoyka** [comment]
I like this. @fatih-yavuz, thoughts?

**Comment by fatih-yavuz** [comment]
I agree, it is a good idea. We can do that. Also, the existing users with problem can be warned as a following step. Feel free to open a PR

**Comment by haliliceylan** [comment]
Does anyone have an idea how to do this, as we can only get the changed lines with git commands, but I don't know how to preserve the syntax of the yaml file.

**Comment by fatih-yavuz** [comment]
I can take a look at it tomorrow evening CET

**Comment by haliliceylan** [comment]
I did some research about that, maybe;

- we can check directly pull request owner Instead of look file changes 

Or

- some magic with git diff ?

Or

- everyone can add new file for domains like halil.yml(links.dev/path) or haliliceylan.yml (gh-username), we can merge and test on ci ?

It's actually make sense because at some point the file will get so big that we won't make any changes (a future problem of course)

Just brain storm.

**Comment by xYundy** [comment]
You can get current production registry.yaml using Git (or just download it  `https://github.com/fatih-yavuz/links.dev/raw/main/registry.yaml`)  to temporary directory.

And now you can directly in NodeJS script calculate the diff and check only newly added users.

**Comment by fatih-yavuz** [comment]
The last approach sounds pretty easy and doable.

**Comment by xYundy** [comment]
@fatih-yavuz I wrote a simple implementation of that behaviour. 

It's behind feature flag (currently directly in script, but I can be also read from cli param or `.env` file if you wish).
