### ISSUE TITLE
Move the backend from Gitlab to GitHub to make this a mono repo

### ISSUE THREAD

**Issue by fatih-yavuz** [fatih-yavuz/links.dev#136]
Research is needed. I built the pipeline on GitLab for the backend. I am not sure about the amount of extra work required if we move it to GitHub. 

Another option is to make it open source on GitLab and link it from here.

**Comment by fatih-yavuz** [comment]
@aliyilmazz we can take a look at this together if you'd like

**Comment by aliyilmazz** [comment]
> @aliyilmazz we can take a look at this together if you'd like

lets take this offline

**Comment by haliliceylan** [comment]
I can help for pipeline movement, I have experience with gitlab CI and various framework deploy. 👋

**Comment by fatih-yavuz** [comment]
@haliliceylan @aliyilmazz I opened a new issue #148 to discuss another approach to this.
