### ISSUE TITLE
Rewrite url's to name just like in registry

### ISSUE THREAD

**Issue by xYundy** [fatih-yavuz/links.dev#147]
Since backend isn't public (or I just can't find it) I make a proposal for new feature.

For now username is not case sensitive and it's render correct page which is great but I think it will be nice if url will be redirected to the case like in `registry.yaml` file. For example:

`links.dev/xyundy` => `links.dev/xYundy`
`links.dev/xyUndy` => `links.dev/xYundy`

I think 301 redirect will be appropriate.

**Comment by bsoyka** [comment]
(To confirm, yes, the backend is private on GitLab.)

**Comment by fatih-yavuz** [comment]
@xYundy, as @bsoyka mentioned it is private on GitLab and we had a plan of moving it here but I opened a new issue #148 to discuss another approach.

**Comment by fatih-yavuz** [comment]
@xYundy the backend is now open-sourced. You can find the link in the README. You can add the logic if you'd like to
