### ISSUE TITLE
Brainstorm: Create a static website with Next.js

### ISSUE THREAD

**Issue by fatih-yavuz** [fatih-yavuz/links.dev#148]
In the backend, there is a Django Application running on two servers and there is a GitLab pipeline running for deployments. I think this is overkill. We don't need that. 

It can be a simple HTML file and be served directly from GitHub without needing servers. I was thinking of moving the backend from GitLab to here but I think this approach is way better.

**Comment by haliliceylan** [comment]
https://github.com/htmlpreview/htmlpreview.github.com

A repository I came across recently, as far as I understand, we can make a static website using JavaScript and a user browser and render the Page.json file of the user. But I'm not sure if we're stuck on CORS, we need to look at the cors options for raw.github.com.

**Comment by itsbrex** [comment]
One other option could be something like John-Doe https://github.com/cadars/john-doe - single-file html sites

**Comment by fatih-yavuz** [comment]
@haliliceylan CORS is not a problem with GitHub Raw.  

@itsbrex It is a good idea but it is a bit away from only link aggregation

**Comment by fatih-yavuz** [comment]
Having a backend also has its own benefits. I am thinking of sticking to the backends after thinking about it. And there is no need to move the backend to GitHub because the GitLab pipeline is fantastic. I open-sourced the backend. You can find the repo on the README
