### ISSUE TITLE
icons.css cdn cache needs invalidated

### ISSUE THREAD

**Issue by itsbrex** [fatih-yavuz/links.dev#151]
> Looks good Brian, thank you

@fatih-yavuz Hmmm, looks like the `?refresh=1` endpoint isn't invalidating some of the cdn files, specifically the `icons.css` file with the new `soundclound` icon:

![image](https://user-images.githubusercontent.com/9772694/210020104-cc786c4b-f36d-4f84-a1ad-3f0ebc9c0e47.png)

- If I manually hit that url with the `?refresh=1` it pulls in the file with the new icon so maybe this is a cloudfare config setting on your end somewhere?

![image](https://user-images.githubusercontent.com/9772694/210020574-30f3aff2-34a6-4063-8e8c-b254f469f18d.png)

_Originally posted by @itsbrex in https://github.com/fatih-yavuz/links.dev/issues/145#issuecomment-1367634571_

**Comment by fatih-yavuz** [comment]
@itsbrex this will be fixed on this PR #155
