### ISSUE TITLE
🧩Feature Request: Add share widget/button

### ISSUE THREAD

**Issue by esau-morais** [fatih-yavuz/links.dev#165]
### Description

Once the project is an alternative based on Linktree since the beginning (correct me if I'm wrong), but I was looking at their current look and there's a sharing button implemented for the user's page.

### Screenshot
![sharing button for the user's page at linktr.ee/theprimeagen](https://user-images.githubusercontent.com/55207584/210188022-035c09fa-21a4-47f5-858c-69dfd5abd2a7.png)
![sharing button after scrolling through the user's page at linktr.ee/theprimeagen](https://user-images.githubusercontent.com/55207584/210188028-f1cb10a4-e25e-42ab-9d34-78e9bdc6eccc.png)

### The Idea

Insert this feature into the project

**Comment by esau-morais** [comment]
> // ℹ️ PS.: I'm able to implement the requested feature if needed.

**Comment by fatih-yavuz** [comment]
@esau-morais you can implement the feature. Let me know if you need any help on the backend.

**Comment by esau-morais** [comment]
This issue has been closing due to the inactivity,
