### ISSUE TITLE
⚡Improvement: Add GitHub template for Issues and PRs

### ISSUE THREAD

**Issue by esau-morais** [fatih-yavuz/links.dev#166]
### Description

If it's worth the effort (once the project's still at the beginning), it'd be great to turn the developer's job easier by doing this (also referring to issue number #164)

### The Idea

GitHub has a feature that can be implemented by the developer to pre-define Issues, PR, etc. The idea is to implement it into the project

### Resources

https://github.com/devspace/awesome-github-templates

https://github.com/dailydotdev/docs/tree/main/.github/ISSUE_TEMPLATE

**Comment by esau-morais** [comment]
> // ℹ️ PS.: I'm able to implement the requested improvement if needed.

**Comment by fatih-yavuz** [comment]
@esau-morais thanks for the suggestion. You can implement it.

**Comment by esau-morais** [comment]
The PR has been merged into the default branch and after @mustafagenc's changes fixing the syntax problem, everything should work as expected now, with that, this issue can be closed.
