### ISSUE TITLE
Warn people with invalid profile pictures

### ISSUE THREAD

**Issue by fatih-yavuz** [fatih-yavuz/links.dev#177]
Each night, run a job to validate the content of people's page.json and their profile images.

If something is wrong, automatically create an issue and tag the person

**Comment by esau-morais** [comment]
Searching more about a workaround to this issue:

1. Run every night

```yaml
on:
  schedule:
    - cron: '0 0 * * *'
```

2. Create an issue and tag the person

Make a POST HTTP request to the GitHub endpoint responsible to create an issue `https://api.github.com/repos/fatih-yavuz/links.dev/issues` (it is needed an authentication token, tho)

3. Validate profile picture

Use `fs` to read the file and `sharp` to validate the metadata

_Alternative:_ Use regEx to validate and conditionally tell what's an image

**Comment by haliliceylan** [comment]
It doesn't make much sense to me to check people all the time, I also think that opening an issue on github can be completely dirty.

We can change the page of users whose profile photos or page.jsons are not correct (a popup or a warning banner)
