### ISSUE TITLE
Add Search Page

### ISSUE THREAD

**Issue by fatih-yavuz** [fatih-yavuz/links.dev#179]
The users can be searchable by their names, description, and links. We can even add a Company & Location section, which can be used for search purposes. 

Do you think something like that would be useful?

**Comment by esau-morais** [comment]
I didn't get where exactly on the website would this be implemented, being honest. Could you please be more specific?

**Comment by fatih-yavuz** [comment]
@esau-morais I imagined a different page on either `links.dev/search` or `search.links.dev` (with this option we can initialize a new repository and work with next or nuxt js)

**Comment by haliliceylan** [comment]
Before that, as a first step, we can make links.dev fully seo compatible, so search engines can index all users' pages. Do we have such support now?

**Comment by fatih-yavuz** [comment]
We have 85 pages indexed @haliliceylan. Regarding the search page, I will close the issue for now and I'd like to observe the user growth a bit.
