### ISSUE TITLE
Issue Template is not working

### ISSUE THREAD

**Issue by mertssmnoglu** [fatih-yavuz/links.dev#185]
I saw that the new issue and pr templates were added by @esau-morais (thanks) i wanted to see how it works.
While we want to submit a [new issue](https://github.com/fatih-yavuz/links.dev/issues/new) it doesn't redirect us to choose.

Example: 
![example](https://user-images.githubusercontent.com/61623638/210863345-0a6c214d-f032-4ec1-8b2c-aa0c44be1c66.png)

I saw there is a syntax error on `.github/ISSUE_TEMPLATE/bug.yaml` and `.github/ISSUE_TEMPLATE/feature.yaml` files.
![syntax-error](https://user-images.githubusercontent.com/61623638/210862955-c9d55931-4f83-42d7-8893-3452aa91cffa.png)

**Comment by esau-morais** [comment]
Thank you for noticing the syntax problem in the merged change by Fatih.

It seems like this is working just fine right now with your last PR, so I'm going to close the Issue for now. If you find anything else that might be breaking, don't hesitate to open an issue

![create new issue page](https://user-images.githubusercontent.com/55207584/210905629-5d3af2b7-53fa-4b49-867a-350edd5a42a9.png)
