### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by furkankapukayaa** [fatih-yavuz/links.dev#193]
### Description

Everything looks fine, but I'm getting an error. Can you check please?

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/56193503/212922490-b8b1fd03-49eb-4cf9-9c0c-ddf851a553af.png)

**Comment by esau-morais** [comment]
![image](https://user-images.githubusercontent.com/55207584/214037541-7a402d8e-e1a8-4604-b127-c19d6ea513ac.png)

This is probably happening because of a typo in your `page.json` file at line 30, which should not have a comma.

**Comment by furkankapukayaa** [comment]
@esau-morais 
I restored it to its original state, but the result did not change.

**Comment by esau-morais** [comment]
Try now

**Comment by furkankapukayaa** [comment]
thanks. my problem is solved.
