### ISSUE TITLE
What is the licence?

### ISSUE THREAD

**Issue by eser** [fatih-yavuz/links.dev#78]
Thank you for this great app @fatih-yavuz. I want to ask you if you have a plan for adding a licence.

**Comment by fatih-yavuz** [comment]
Thanks, @eser, I don't have anything in my mind. What do you think about MIT?

**Comment by eser** [comment]
I prefer MIT but it is very permissive.
It is up to you how you wanted use this repo.

Disclaimer! I really liked the design. (I know it is very simple but I am really lazy to recreate it 😅). I wanted use for my personal site deployed statically with my custom domain.

**Comment by fatih-yavuz** [comment]
You can actually use your own domain. Just add a CNAME to map your domain to links.dev/eser. 

Is there any specific reason why you asked about the license? Or, did you just want to contribute?

**Comment by bsoyka** [comment]
@fatih-yavuz Adding a license is what truly makes your code open-source, legally allowing people to copy and change it. Probably something to get out of the way sooner rather than later, plus fairly simple to do. I can even throw it in if you want.

**Comment by millette** [comment]
See also https://choosealicense.com/ (by github).
