### ISSUE TITLE
Support master branch for page.json

### ISSUE THREAD

**Issue by fatih-yavuz** [fatih-yavuz/links.dev#84]
Currently, the system looks for a branch called `main` for your my-links page.json file. It's also intuitive to create a `master` branch. We should support `master` branch as well

**Comment by esau-morais** [comment]
Maybe instead of supporting a specific name, why not just try to figure out what is the `default` one?

**Comment by bsoyka** [comment]
The GitHub API supports this, just [getting the repo details](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository) and taking the `default_branch` property.

**Comment by fatih-yavuz** [comment]
Currently, the backend doesn't rely on the official API but instead makes a curl to https://raw.githubusercontent.com/whatever-the-rest-is

This is a good idea @esau-morais.

I haven't read the GitHub API and its limitations yet @bsoyka I am concerned about the rate limits.

I am going to conflict with my initial thought on this issue but here it is:
We already force the user to have certain things like the repo name, the filename etc. Why cannot the branch name "main" be one of them? This is the simplest and most convenient solution.

**Comment by esau-morais** [comment]
Yea, it makes sense, once this is a developer-friendly project in its starting progress, making sure the client follow rules is a great idea. Although it would be great turn things more flexible in the future.
